#!/usr/bin/env bash
# Displays information about subdomains.

# Variables & Parameters
subdomains=("www" "lb-01" "web-01" "web-02")
domain="$1"
sub="$2"

dig_cmd () {
    # Function to retrieve subdomain information using dig command
    # Arguments:
    #   $1: domain
    #   $2: subdomain
    sub="$2"
    INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
    IP=$(echo "$INFO" | awk '{print $5}')
    RECORD=$(echo "$INFO" | awk '{print $4}')

    echo "The subdomain $sub is a $RECORD record and points to $IP"
}

# Main script
if [ $# -eq 1 ]; then
    # When only domain parameter is provided
    for subs in "${subdomains[@]}"; do
        dig_cmd "$domain" "$subs"
    done
elif [ $# -eq 2 ]; then
    # When both domain and subdomain parameters are provided
    dig_cmd "$domain" "$sub"
fi
