#!/usr/bin/env bash

# This script installs and configures Nginx web server on Ubunt

# Install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart
