#!/usr/bin/env bash
# Script to install and configure Nginx for redirection
# Nginx should be listening on port 80 and redirect /redirect_me to another page

# Update the package repositories
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create the index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define the string for replacement in the Nginx configuration file
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/alxafrica.com permanent;"

# Replace the specified line in the Nginx configuration file with the new string
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
sudo service nginx restart