#!/bin/bash

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Allow Nginx HTTP traffic in the firewall (ufw)
sudo ufw allow 'Nginx HTTP'

# Create index.html with a "Hello World" message
echo "Hello World - Web Server 2" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx to redirect /redirect_me to a specific URL
new_string="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Create a custom 404.html page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404.html page
new_string="listen 80 default_server;\\nerror_page 404 \/404.html;\\n\\tlocation = \/404.html {\\n\\t\\troot \/usr\/share\/nginx\/html;\\n\\t\\tinternal;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Add a custom response header with the server hostname
custom_header="add_header X-Served-By \$hostname;"
sudo sed -i "/http {/a $custom_header" /etc/nginx/nginx.conf

# Start the Nginx service
sudo systemctl start nginx
