#!/usr/bin/env bash
# Configures Nginx to listen on port 80

# Remove the default symbolic link to the Nginx configuration
rm /etc/nginx/sites-enabled/default

# Create a new symbolic link pointing to the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Change the default configuration to listen on port 80
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the configuration changes
service nginx restart
