#!/usr/bin/env bash

# Displays "To infinity and beyond" indefinitely with
# a sleep 2 in between each iteration.
# Displays "I am invincible!!!" in between each iteration.

# Function to handle SIGTERM signal
handle_sigterm() {
  echo "I am invincible!!!"
}

# Register the SIGTERM signal handler
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done

