#!/usr/bin/env bash
# This script runs Nginx as the user "nginx" instead of the default user.

# Enable debugging output to see each command as it is executed
set -x

# Kill any running apache2 processes to avoid port conflicts with Nginx
pkill apache2

# Modify the nginx.conf file to set the user as "nginx"
# This ensures Nginx runs as the user "nginx" instead of the default user
# A backup file with the extension ".bak" is created with the original configuration
sed -i.bak '2s/^/user nginx;\n/' /etc/nginx/nginx.conf

# Modify the default Nginx configuration file to use port 8080 instead of 80
sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default

# Change the owner and add read permission to the nginx.conf file
# The file needs to be accessible by the "nginx" user
sudo chmod u+r /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

# Start the Nginx service as the user "nginx" using sudo
sudo -u nginx service nginx start
