#!/usr/bin/env bash
# Gracefully reloads Gunicorn - restart gunicorn workers
#shellcheck disable=SC2009

# Get the process IDs of Gunicorn workers
worker_pids=$(pgrep gunicorn)

if [[ -n "$worker_pids" ]]; then
    # Send SIGHUP signal to each worker process
    for pid in $worker_pids; do
        kill -HUP "$pid"
    done
    echo "Gunicorn workers gracefully reloaded."
else
    echo "No Gunicorn workers found."
fi
